pub const DOC_HT_SIZE: usize = 50000;
pub const GLOB_HT_SIZE: usize = 350000;
pub const WEIGHT_MULTIPLIER: f64 = 100000000.0;
pub const TERM_LENGTH: usize = 16;
pub const DOC_ID_LENGTH: usize = 3;
pub const WEIGHT_LENGTH: usize = 9;
pub const MAP_NAME_LENGTH: usize = 13;
pub const POST_RECORD_SIZE: usize = DOC_ID_LENGTH + WEIGHT_LENGTH + 2;
pub const MAP_RECORD_SIZE: usize = MAP_NAME_LENGTH + 1;
